export const problems = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    acceptanceRate: "49.5%",
    companies: ["Google", "Amazon", "Microsoft", "Apple", "Facebook"],
    tags: ["Array", "Hash Table"],
    problemType: "Array",
    description:
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    acceptanceRate: "38.2%",
    companies: ["Amazon", "Microsoft", "Bloomberg", "Adobe"],
    tags: ["Linked List", "Math", "Recursion"],
    problemType: "Linked List",
    description:
      "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit.",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    acceptanceRate: "33.8%",
    companies: ["Amazon", "Google", "Microsoft", "Bloomberg"],
    tags: ["Hash Table", "String", "Sliding Window"],
    problemType: "String",
    description:
      "Given a string s, find the length of the longest substring without repeating characters.",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    acceptanceRate: "35.2%",
    companies: ["Google", "Microsoft", "Amazon", "Apple"],
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    problemType: "Array",
    description:
      "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    acceptanceRate: "32.1%",
    companies: ["Amazon", "Google", "Microsoft", "Facebook"],
    tags: ["String", "Dynamic Programming"],
    problemType: "String",
    description:
      "Given a string s, return the longest palindromic substring in s.",
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    difficulty: "Medium",
    acceptanceRate: "42.3%",
    companies: ["Amazon", "Microsoft"],
    tags: ["String"],
    problemType: "String",
    description:
      "The string 'PAYPALISHIRING' is written in a zigzag pattern on a given number of rows.",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Easy",
    acceptanceRate: "27.8%",
    companies: ["Amazon", "Microsoft", "Apple"],
    tags: ["Math"],
    problemType: "Math",
    description:
      "Given a signed 32-bit integer x, return x with its digits reversed.",
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    acceptanceRate: "16.9%",
    companies: ["Amazon", "Microsoft", "Google"],
    tags: ["String", "Math"],
    problemType: "String",
    description:
      "Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer.",
  },
  {
    id: 9,
    title: "Palindrome Number",
    difficulty: "Easy",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Microsoft", "Apple"],
    tags: ["Math"],
    problemType: "Math",
    description:
      "Given an integer x, return true if x is a palindrome, and false otherwise.",
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    acceptanceRate: "27.4%",
    companies: ["Google", "Microsoft", "Amazon"],
    tags: ["String", "Dynamic Programming", "Recursion"],
    problemType: "Dynamic Programming",
    description:
      "Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*'.",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    acceptanceRate: "54.3%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers", "Greedy"],
    problemType: "Two Pointers",
    description:
      "Given n non-negative integers height where each represents a point at coordinate (i, height[i]).",
  },
  {
    id: 12,
    title: "Integer to Roman",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Microsoft"],
    tags: ["Hash Table", "Math", "String"],
    problemType: "Math",
    description: "Given an integer, convert it to a roman numeral.",
  },
  {
    id: 13,
    title: "Roman to Integer",
    difficulty: "Easy",
    acceptanceRate: "58.2%",
    companies: ["Amazon", "Microsoft", "Apple"],
    tags: ["Hash Table", "Math", "String"],
    problemType: "Math",
    description: "Given a roman numeral, convert it to an integer.",
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    acceptanceRate: "40.1%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Trie"],
    problemType: "String",
    description:
      "Write a function to find the longest common prefix string amongst an array of strings.",
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers", "Sorting"],
    problemType: "Two Pointers",
    description:
      "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",
  },
  {
    id: 16,
    title: "3Sum Closest",
    difficulty: "Medium",
    acceptanceRate: "45.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Two Pointers", "Sorting"],
    problemType: "Two Pointers",
    description:
      "Given an integer array nums of length n and an integer target, find three integers in nums such that the sum is closest to target.",
  },
  {
    id: 17,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    acceptanceRate: "52.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Hash Table", "String", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent.",
  },
  {
    id: 18,
    title: "4Sum",
    difficulty: "Medium",
    acceptanceRate: "37.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Two Pointers", "Sorting"],
    problemType: "Two Pointers",
    description:
      "Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]] such that a, b, c, and d are distinct.",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    acceptanceRate: "39.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Linked List", "Two Pointers"],
    problemType: "Linked List",
    description:
      "Given the head of a linked list, remove the nth node from the end of the list and return its head.",
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    acceptanceRate: "40.1%",
    companies: ["Amazon", "Google", "Microsoft", "Facebook"],
    tags: ["String", "Stack"],
    problemType: "Stack",
    description:
      "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Linked List", "Recursion"],
    problemType: "Linked List",
    description:
      "Merge two sorted linked lists and return it as a sorted list.",
  },
  {
    id: 22,
    title: "Generate Parentheses",
    difficulty: "Medium",
    acceptanceRate: "70.2%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["String", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
  },
  {
    id: 23,
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    acceptanceRate: "47.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Linked List", "Divide and Conquer", "Heap"],
    problemType: "Heap",
    description:
      "You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.",
  },
  {
    id: 24,
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Linked List", "Recursion"],
    problemType: "Linked List",
    description:
      "Given a linked list, swap every two adjacent nodes and return its head.",
  },
  {
    id: 25,
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    acceptanceRate: "48.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Linked List", "Recursion"],
    problemType: "Linked List",
    description:
      "Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.",
  },
  {
    id: 26,
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    acceptanceRate: "48.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers"],
    problemType: "Array",
    description:
      "Given a sorted array nums, remove the duplicates in-place such that each element appears only once and returns the new length.",
  },
  {
    id: 27,
    title: "Remove Element",
    difficulty: "Easy",
    acceptanceRate: "51.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Two Pointers"],
    problemType: "Array",
    description:
      "Given an array nums and a value val, remove all instances of that value in-place and return the new length.",
  },
  {
    id: 28,
    title: "Find the Index of the First Occurrence in a String",
    difficulty: "Easy",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Two Pointers"],
    problemType: "String",
    description:
      "Given two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.",
  },
  {
    id: 29,
    title: "Divide Two Integers",
    difficulty: "Medium",
    acceptanceRate: "17.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Math", "Bit Manipulation"],
    problemType: "Math",
    description:
      "Given two integers dividend and divisor, divide two integers without using multiplication, division, and mod operator.",
  },
  {
    id: 30,
    title: "Substring with Concatenation of All Words",
    difficulty: "Hard",
    acceptanceRate: "28.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Hash Table", "Sliding Window"],
    problemType: "String",
    description:
      "You are given a string s and an array of strings words. All the strings of words are of the same length.",
  },
  {
    id: 31,
    title: "Next Permutation",
    difficulty: "Medium",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers"],
    problemType: "Array",
    description:
      "Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.",
  },
  {
    id: 32,
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    acceptanceRate: "32.1%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Dynamic Programming", "Stack"],
    problemType: "Dynamic Programming",
    description:
      "Given a string containing just the characters '(' and ')', find the length of the longest valid (well-formed) parentheses substring.",
  },
  {
    id: 33,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    acceptanceRate: "38.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Binary Search"],
    problemType: "Binary Search",
    description:
      "There is an integer array nums sorted in ascending order (with distinct values).",
  },
  {
    id: 34,
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    acceptanceRate: "40.2%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Binary Search"],
    problemType: "Binary Search",
    description:
      "Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.",
  },
  {
    id: 35,
    title: "Search Insert Position",
    difficulty: "Easy",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Binary Search"],
    problemType: "Binary Search",
    description:
      "Given a sorted array of distinct integers and a target value, return the index if the target is found.",
  },
  {
    id: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    acceptanceRate: "54.2%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Hash Table", "Matrix"],
    problemType: "Hash Table",
    description:
      "Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules.",
  },
  {
    id: 37,
    title: "Sudoku Solver",
    difficulty: "Hard",
    acceptanceRate: "52.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Backtracking", "Matrix"],
    problemType: "Backtracking",
    description:
      "Write a program to solve a Sudoku puzzle by filling the empty cells.",
  },
  {
    id: 38,
    title: "Count and Say",
    difficulty: "Medium",
    acceptanceRate: "47.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String"],
    problemType: "String",
    description:
      "The count-and-say sequence is a sequence of digit strings defined by the recursive formula.",
  },
  {
    id: 39,
    title: "Combination Sum",
    difficulty: "Medium",
    acceptanceRate: "62.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target.",
  },
  {
    id: 40,
    title: "Combination Sum II",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target.",
  },
  {
    id: 41,
    title: "First Missing Positive",
    difficulty: "Hard",
    acceptanceRate: "35.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Hash Table"],
    problemType: "Array",
    description:
      "Given an unsorted integer array nums, return the smallest missing positive integer.",
  },
  {
    id: 42,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack"],
    problemType: "Dynamic Programming",
    description:
      "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
  },
  {
    id: 43,
    title: "Multiply Strings",
    difficulty: "Medium",
    acceptanceRate: "37.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Math", "String", "Simulation"],
    problemType: "Math",
    description:
      "Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.",
  },
  {
    id: 44,
    title: "Wildcard Matching",
    difficulty: "Hard",
    acceptanceRate: "27.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Dynamic Programming", "Greedy"],
    problemType: "Dynamic Programming",
    description:
      "Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*'.",
  },
  {
    id: 45,
    title: "Jump Game II",
    difficulty: "Medium",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Dynamic Programming", "Greedy"],
    problemType: "Dynamic Programming",
    description:
      "Given an array of non-negative integers nums, you are initially positioned at the first index of the array.",
  },
  {
    id: 46,
    title: "Permutations",
    difficulty: "Medium",
    acceptanceRate: "72.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.",
  },
  {
    id: 47,
    title: "Permutations II",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given a collection of numbers, nums, that might contain duplicates, return all possible unique permutations in any order.",
  },
  {
    id: 48,
    title: "Rotate Image",
    difficulty: "Medium",
    acceptanceRate: "68.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Math", "Matrix"],
    problemType: "Array",
    description:
      "You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).",
  },
  {
    id: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    acceptanceRate: "67.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Hash Table", "String", "Sorting"],
    problemType: "Hash Table",
    description:
      "Given an array of strings strs, group the anagrams together. You can return the answer in any order.",
  },
  {
    id: 50,
    title: "Pow(x, n)",
    difficulty: "Medium",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Math", "Recursion"],
    problemType: "Math",
    description:
      "Implement pow(x, n), which calculates x raised to the power n (i.e., x^n).",
  },
  {
    id: 51,
    title: "N-Queens",
    difficulty: "Hard",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.",
  },
  {
    id: 52,
    title: "N-Queens II",
    difficulty: "Hard",
    acceptanceRate: "68.2%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Backtracking"],
    problemType: "Backtracking",
    description:
      "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.",
  },
  {
    id: 53,
    title: "Maximum Subarray",
    difficulty: "Medium",
    acceptanceRate: "49.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Divide and Conquer", "Dynamic Programming"],
    problemType: "Dynamic Programming",
    description:
      "Given an integer array nums, find the subarray with the largest sum, and return its sum.",
  },
  {
    id: 54,
    title: "Spiral Matrix",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Matrix", "Simulation"],
    problemType: "Array",
    description:
      "Given an m x n matrix, return all elements of the matrix in spiral order.",
  },
  {
    id: 55,
    title: "Jump Game",
    difficulty: "Medium",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Dynamic Programming", "Greedy"],
    problemType: "Dynamic Programming",
    description:
      "You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.",
  },
  {
    id: 56,
    title: "Merge Intervals",
    difficulty: "Medium",
    acceptanceRate: "45.2%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Sorting"],
    problemType: "Array",
    description:
      "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",
  },
  {
    id: 57,
    title: "Insert Interval",
    difficulty: "Medium",
    acceptanceRate: "38.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array"],
    problemType: "Array",
    description:
      "You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti.",
  },
  {
    id: 58,
    title: "Length of Last Word",
    difficulty: "Easy",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String"],
    problemType: "String",
    description:
      "Given a string s consisting of words and spaces, return the length of the last word in the string.",
  },
  {
    id: 59,
    title: "Spiral Matrix II",
    difficulty: "Medium",
    acceptanceRate: "68.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Matrix", "Simulation"],
    problemType: "Array",
    description:
      "Given a positive integer n, generate an n x n matrix filled with elements from 1 to n² in spiral order.",
  },
  {
    id: 60,
    title: "Permutation Sequence",
    difficulty: "Hard",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Math", "Recursion"],
    problemType: "Math",
    description:
      "The set [1, 2, 3, ..., n] contains a total of n! unique permutations.",
  },
  {
    id: 61,
    title: "Rotate List",
    difficulty: "Medium",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Linked List", "Two Pointers"],
    problemType: "Linked List",
    description:
      "Given the head of a linked list, rotate the list to the right by k places.",
  },
  {
    id: 62,
    title: "Unique Paths",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Math", "Dynamic Programming", "Combinatorics"],
    problemType: "Dynamic Programming",
    description:
      "There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]).",
  },
  {
    id: 63,
    title: "Unique Paths II",
    difficulty: "Medium",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Dynamic Programming", "Matrix"],
    problemType: "Dynamic Programming",
    description:
      "You are given an m x n integer array obstacleGrid. There is a robot initially located at the top-left corner (i.e., obstacleGrid[0][0]).",
  },
  {
    id: 64,
    title: "Minimum Path Sum",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Dynamic Programming", "Matrix"],
    problemType: "Dynamic Programming",
    description:
      "Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path.",
  },
  {
    id: 65,
    title: "Valid Number",
    difficulty: "Hard",
    acceptanceRate: "18.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String"],
    problemType: "String",
    description:
      "A valid number can be split up into these components (in order): 1. A decimal number or integer 2. (Optional) An 'e' or 'E', followed by an integer.",
  },
  {
    id: 66,
    title: "Plus One",
    difficulty: "Easy",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Math"],
    problemType: "Array",
    description:
      "You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer.",
  },
  {
    id: 67,
    title: "Add Binary",
    difficulty: "Easy",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Math", "String", "Bit Manipulation"],
    problemType: "String",
    description:
      "Given two binary strings a and b, return their sum as a binary string.",
  },
  {
    id: 68,
    title: "Text Justification",
    difficulty: "Hard",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Simulation"],
    problemType: "String",
    description:
      "Given an array of strings words and a width maxWidth, format the text such that each line has exactly maxWidth characters and is fully (left and right) justified.",
  },
  {
    id: 69,
    title: "Sqrt(x)",
    difficulty: "Easy",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Math", "Binary Search"],
    problemType: "Math",
    description:
      "Given a non-negative integer x, return the square root of x rounded down to the nearest integer.",
  },
  {
    id: 70,
    title: "Climbing Stairs",
    difficulty: "Easy",
    acceptanceRate: "51.2%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Dynamic Programming", "Math"],
    problemType: "Dynamic Programming",
    description:
      "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps.",
  },
  {
    id: 71,
    title: "Simplify Path",
    difficulty: "Medium",
    acceptanceRate: "37.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Stack"],
    problemType: "Stack",
    description:
      "Given a string path, which is an absolute path (starting with a slash '/') to a file or directory in a Unix-style file system, convert it to the simplified canonical path.",
  },
  {
    id: 72,
    title: "Edit Distance",
    difficulty: "Hard",
    acceptanceRate: "52.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["String", "Dynamic Programming"],
    problemType: "Dynamic Programming",
    description:
      "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.",
  },
  {
    id: 73,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    acceptanceRate: "48.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Hash Table", "Matrix"],
    problemType: "Array",
    description:
      "Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's.",
  },
  {
    id: 74,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Binary Search", "Matrix"],
    problemType: "Binary Search",
    description:
      "Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix.",
  },
  {
    id: 75,
    title: "Sort Colors",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers", "Sorting"],
    problemType: "Two Pointers",
    description:
      "Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent.",
  },
  {
    id: 76,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["String", "Hash Table", "Sliding Window"],
    problemType: "Sliding Window",
    description:
      "Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.",
  },
  {
    id: 77,
    title: "Combinations",
    difficulty: "Medium",
    acceptanceRate: "68.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking"],
    problemType: "Backtracking",
    description:
      "Given two integers n and k, return all possible combinations of k numbers chosen from the range [1, n].",
  },
  {
    id: 78,
    title: "Subsets",
    difficulty: "Medium",
    acceptanceRate: "72.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    problemType: "Backtracking",
    description:
      "Given an integer array nums of unique elements, return all possible subsets (the power set).",
  },
  {
    id: 79,
    title: "Word Search",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Backtracking", "Matrix"],
    problemType: "Backtracking",
    description:
      "Given an m x n grid of characters board and a string word, return true if word exists in the grid.",
  },
  {
    id: 80,
    title: "Remove Duplicates from Sorted Array II",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Two Pointers"],
    problemType: "Array",
    description:
      "Given an integer array nums sorted in non-decreasing order, remove some duplicates in-place such that each unique element appears at most twice.",
  },
  {
    id: 81,
    title: "Search in Rotated Sorted Array II",
    difficulty: "Medium",
    acceptanceRate: "35.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Binary Search"],
    problemType: "Binary Search",
    description:
      "There is an integer array nums sorted in non-decreasing order (not necessarily with distinct values).",
  },
  {
    id: 82,
    title: "Remove Duplicates from Sorted List II",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Linked List", "Two Pointers"],
    problemType: "Linked List",
    description:
      "Given the head of a sorted linked list, delete all nodes that have duplicate numbers, leaving only distinct numbers from the original list.",
  },
  {
    id: 83,
    title: "Remove Duplicates from Sorted List",
    difficulty: "Easy",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Linked List"],
    problemType: "Linked List",
    description:
      "Given the head of a sorted linked list, delete all duplicates such that each element appears only once.",
  },
  {
    id: 84,
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Stack", "Monotonic Stack"],
    problemType: "Stack",
    description:
      "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
  },
  {
    id: 85,
    title: "Maximal Rectangle",
    difficulty: "Hard",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Dynamic Programming", "Stack", "Matrix"],
    problemType: "Dynamic Programming",
    description:
      "Given a rows x cols binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's and return its area.",
  },
  {
    id: 86,
    title: "Partition List",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Linked List", "Two Pointers"],
    problemType: "Linked List",
    description:
      "Given the head of a linked list and a value x, partition it such that all nodes less than x come before nodes greater than or equal to x.",
  },
  {
    id: 87,
    title: "Scramble String",
    difficulty: "Hard",
    acceptanceRate: "35.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Dynamic Programming"],
    problemType: "Dynamic Programming",
    description:
      "We can scramble a string s to get a string t using the following algorithm.",
  },
  {
    id: 88,
    title: "Merge Sorted Array",
    difficulty: "Easy",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Array", "Two Pointers", "Sorting"],
    problemType: "Array",
    description:
      "You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.",
  },
  {
    id: 89,
    title: "Gray Code",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Math", "Backtracking", "Bit Manipulation"],
    problemType: "Math",
    description:
      "An n-bit gray code sequence is a sequence of 2n integers where every integer is in the range [0, 2n - 1] inclusive.",
  },
  {
    id: 90,
    title: "Subsets II",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    problemType: "Backtracking",
    description:
      "Given an integer array nums that may contain duplicates, return all possible subsets (the power set).",
  },
  {
    id: 91,
    title: "Decode Ways",
    difficulty: "Medium",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["String", "Dynamic Programming"],
    problemType: "Dynamic Programming",
    description:
      "A message containing letters from A-Z can be encoded into numbers using the following mapping.",
  },
  {
    id: 92,
    title: "Reverse Linked List II",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Linked List"],
    problemType: "Linked List",
    description:
      "Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes from position left to position right, and return the reversed list.",
  },
  {
    id: 93,
    title: "Restore IP Addresses",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Backtracking"],
    problemType: "Backtracking",
    description:
      "A valid IP address consists of exactly four integers separated by single dots. Each integer is between 0 and 255 (inclusive) and cannot have leading zeros.",
  },
  {
    id: 94,
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    acceptanceRate: "68.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    problemType: "Tree",
    description:
      "Given the root of a binary tree, return the inorder traversal of its nodes' values.",
  },
  {
    id: 95,
    title: "Unique Binary Search Trees II",
    difficulty: "Medium",
    acceptanceRate: "52.3%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Dynamic Programming", "Tree", "Binary Search Tree"],
    problemType: "Dynamic Programming",
    description:
      "Given an integer n, return all the structurally unique BST's (binary search trees), which has exactly n nodes of unique values from 1 to n.",
  },
  {
    id: 96,
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Math", "Dynamic Programming", "Tree"],
    problemType: "Dynamic Programming",
    description:
      "Given an integer n, return the number of structurally unique BST's (binary search trees) which has exactly n nodes of unique values from 1 to n.",
  },
  {
    id: 97,
    title: "Interleaving String",
    difficulty: "Medium",
    acceptanceRate: "35.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["String", "Dynamic Programming"],
    problemType: "Dynamic Programming",
    description:
      "Given strings s1, s2, and s3, find whether s3 is formed by an interleaving of s1 and s2.",
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    acceptanceRate: "32.8%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Tree", "Depth-First Search", "Binary Search Tree"],
    problemType: "Tree",
    description:
      "Given the root of a binary tree, determine if it is a valid binary search tree (BST).",
  },
  {
    id: 99,
    title: "Recover Binary Search Tree",
    difficulty: "Medium",
    acceptanceRate: "42.8%",
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Tree", "Depth-First Search", "Binary Search Tree"],
    problemType: "Tree",
    description:
      "You are given the root of a binary search tree (BST), where the values of exactly two nodes of the tree were swapped by mistake.",
  },
  {
    id: 100,
    title: "Same Tree",
    difficulty: "Easy",
    acceptanceRate: "58.9%",
    companies: ["Amazon", "Google", "Microsoft", "Apple"],
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    problemType: "Tree",
    description:
      "Given the roots of two binary trees p and q, write a function to check if they are the same or not.",
  },
];
